=== JozsefHorvath/DynamicsCRM-Automation/src/CmdletProviders/Connections.Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Name": {
        "type": "string"
      },
      "DiscoveryUrl": {
        "type": "string"
      },
      "UserName": {
        "type": "string"
      },
      "Password": {
        "type": "string"
      },
      "Organizations": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "Name": {
              "type": "string"
            },
            "ConnectionString": {
              "type": "string"
            }
          },
          "required": [
            "Name",
            "ConnectionString"
          ]
        }
      }
    },
    "required": [
      "Name",
      "DiscoveryUrl",
      "UserName",
      "Password",
      "Organizations"
    ]
  }
}

=== JozsefHorvath/DynamicsCRM-Automation/src/CmdletProviders/Connections.json
[
  {
    "Name": "MyOnlineDeployment",
    "DiscoveryUrl": "https://disco.crm4.dynamics.com",
    "UserName": "administrator@MyOnlineDeployment.com",
    "Password": "password",
    "Organizations": [
      {
        "Name": "organization1",
        "ConnectionString": "Url=https://organization1.crm4.dynamics.com; Username=administrator@MyOnlineDeployment.com; Password=password; authtype=Office365"
      },
      {
        "Name": "organization2",
        "ConnectionString": "Url=https://organization2.crm4.dynamics.com; Username=administrator@MyOnlineDeployment.com; Password=password; authtype=Office365"
      }
    ]
  },
  {
    "Name": "MyOnPremiseDeployment",
    "DiscoveryUrl": "https://myonpremisedeployment.domain.com",
    "UserName": "domain\\Administrator",
    "Password": "password",
    "Organizations": [
      {
        "Name": "MyOnPremiseDeployment Integration",
        "ConnectionString": "Url=https://myonpremisedeployment.domain.com/Integration; Domain=domain; Username=Administrator; Password=password; authtype=AD"
      }
    ]
  }
]
